# Project information
site_name: 'Pinry Docs'
site_description: 'Docs for the Pinry project.'
site_author: "Pinry's Contributors"
site_url: 'https://pinry.github.io/pinry/'

# Repository
repo_name: 'pinry/pinry'
repo_url: 'https://github.com/pinry/pinry'

# Copyright
copyright: "Copyright &copy; 2019 Pinry's Contributors"

# Navigation
nav:
  - Home: 'index.md'
  - Screenshots: 'screenshots.md'
  - Extensions: 'extensions.md'
  - Theories: 'theories.md'
  - Install with Docker: 'install-with-docker.md'
  - Development: 'development.md'
  - API support: 'api.md'
  - Plugin System: 'plugin-system.md'
  - Upgrade Guide: 'upgrade-guide.md'
  - Docs: 'docs.md'
  - Passwords: 'passwords.md'
  - Assets: 'assets.md'
  - Contributing: 'contributing.md'
  - License: 'license.md'

# Configuration
docs_dir: 'docs/src'
site_dir: 'docs/dist'
edit_uri: 'edit/master/docs/src/'
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Customization
extra:
  analytics:
    provider: google
    property: G-5LWLDK598X
  manifest: 'manifest.webmanifest'
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/pinry/pinry'

markdown_extensions:
  - codehilite
  - toc:
      permalink: true
