# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-22 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pin_referer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='origin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='referer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
