# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-22 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('core', '0002_pin_referer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pin',
            name='origin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='referer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='pins',
            field=models.ManyToManyField(blank=True, related_name='pins', to='core.Pin'),
        ),
        migrations.AddField(
            model_name='board',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together=set([('submitter', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='board',
            index_together=set([('submitter', 'name')]),
        ),
    ]
