# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-15 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190222_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='origin',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='referer',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
