# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-22 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('core', '0003_auto_20190222_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('pins', models.ManyToManyField(blank=True, related_name='pins', to='core.Pin')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together=set([('submitter', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='board',
            index_together=set([('submitter', 'name')]),
        ),
    ]
