# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-22 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190715_0912'),
        ('core', '0004_auto_20190222_1451'),
    ]

    operations = [
    ]
