# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-11 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20191122_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='origin',
        ),
    ]
