# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-11 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_pin_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
