# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-11 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pin_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
