# Generated by Django 2.2.14 on 2020-08-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_board_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='referer',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
