# Generated by Django 2.2.14 on 2021-03-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200825_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='referer',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
