<template>
  <div class="pins">
    <section class="section">
      <div id="pins-container" class="container" v-if="blocks">
        <div
          v-masonry=""
          transition-duration="0.3s"
          item-selector=".grid-item"
          column-width=".grid-sizer"
          gutter=".gutter-sizer"
        >
          <template v-for="item in blocks">
            <div v-bind:key="item.id" v-masonry-tile class="grid">
              <div class="grid-sizer"></div>
              <div class="gutter-sizer"></div>
              <div class="pin-card grid-item">
                <img :src="item.url"
                     @click="openPreview(item)"
                     alt="item.description"
                     class="pin-preview-image">
                <div class="pin-footer">
                  <div class="description" v-show="item.description"><p>{{ item.description }}</p></div>
                  <div class="details">
                    <div class="is-pulled-left">
                      <img class="avatar" :src="item.avatar" alt="">
                    </div>
                    <div class="pin-info">
                      <span class="dim">pined by&nbsp;<span><router-link to="/">{{ item.author }}</router-link></span>
                        <template v-if="item.tags.length > 0">
                          &nbsp;in&nbsp;
                          <template v-for="tag in item.tags">
                            <span v-bind:key="tag" class="pin-tag">
                              &nbsp;
                              <router-link to="/tags/">{{ tag }}</router-link>
                            </span>
                          </template>
                        </template>
                      </span>
                    </div>
                    <div class="is-clearfix"></div>
                  </div>
                </div>
              </div>
            </div>
          </template>
        </div>
      </div>
    </section>
  </div>
</template>

<script>
import API from './api';
import pinHandler from './utils/PinHandler';
import PinPreview from './PinPreview.vue';

function createImageItem(pin) {
  const image = {};
  image.url = pinHandler.escapeUrl(pin.image.thumbnail.image);
  image.id = pin.id;
  image.description = pin.description;
  image.tags = pin.tags;
  image.author = pin.submitter.username;
  image.avatar = `//gravatar.com/avatar/${pin.submitter.gravatar}`;
  image.original_url = pin.image.image;
  image.orgianl_width = pin.image.width;
  return image;
}

export default {
  name: 'pins',
  components: {},
  data() {
    return {
      blocks: [],
    };
  },
  methods: {
    buildBlocks(results) {
      const blocks = [];
      results.forEach(
        (pin) => {
          blocks.push(
            createImageItem(pin),
          );
        },
      );
      return blocks;
    },
    openPreview(pinItem) {
      this.$buefy.modal.open(
        {
          parent: this,
          component: PinPreview,
          props: {
            pinItem,
          },
          // width: pinItem.orgianl_width,
          hasModalCard: true,
          customClass: 'pin-preview-at-home',
        },
      );
    },
  },
  created() {
    API.fetchPins(0).then(
      (resp) => {
        this.blocks = this.buildBlocks(resp.data.results);
      },
    );
  },
};
</script>

<style lang="scss" scoped>
/* grid */
.grid-sizer,
.grid-item { width: 240px; }
.grid-item {
  margin-bottom: 15px;
}
.gutter-sizer {
  width: 15px;
}
/* card */
$pin-footer-position-fix: -6px;
$avatar-width: 30px;
$avatar-height: 30px;

@mixin pin-detail-font-size{
  font-size: 12px;
}

@mixin description-font {
  @include pin-detail-font-size;
  font-family: 'Georgia', 'Times', 'Times New Roman', serif;
}

@mixin secondary-font {
  @include pin-detail-font-size;
  color: #999;
  font-weight: normal;
}

.pin-card{
  .pin-preview-image {
    cursor: pointer;
  }
  > img {
    border-radius: 3px 3px 0 0;
  }
  .avatar {
    height: $avatar-height;
    width: $avatar-width;
    border-radius: 3px;
  }
}
.pin-footer {
  position: relative;
  top: $pin-footer-position-fix;
  background-color: white;
  border-radius: 0 0 3px 3px ;
  box-shadow: 0 1px 0 #bbb;
  .description {
    @include description-font;
    padding: 8px;
    border-bottom: 1px solid #DDDDDD;
    overflow: hidden;
    text-overflow: ellipsis;
  }
  .details {
    @include secondary-font;
    padding: 10px;
    > .pin-info {
      line-height: 16px;
      width: 220px;
      padding-left: $avatar-width + 5px;
    }
    .pin-info a {
      font-weight: bold;
    }
  }
}

/*pin container size fit*/
/* Generated by python code:
/* def fn(x):
/*     gutter = 15
/*     image_width = 240
/*     border_width_of_parent = 24
/*     size = image_width * x + gutter * (x - 1)
/*     width = size + border_width_of_parent * 2
/*     print(template % (width, size))
/*
/* for i in range(1, 12):
/*     fn(i)
*/

@media screen and (min-width: 288px) {
  #pins-container {
    max-width: 240px;
  }
}
@media screen and (min-width: 543px) {
  #pins-container {
    max-width: 495px;
  }
}
@media screen and (min-width: 798px) {
  #pins-container {
    max-width: 750px;
  }
}
@media screen and (min-width: 1053px) {
  #pins-container {
    max-width: 1005px;
  }
}
@media screen and (min-width: 1308px) {
  #pins-container {
    max-width: 1260px;
  }
}
@media screen and (min-width: 1563px) {
  #pins-container {
    max-width: 1515px;
  }
}
@media screen and (min-width: 1818px) {
  #pins-container {
    max-width: 1770px;
  }
}
@media screen and (min-width: 2073px) {
  #pins-container {
    max-width: 2025px;
  }
}
@media screen and (min-width: 2328px) {
  #pins-container {
    max-width: 2280px;
  }
}
@media screen and (min-width: 2583px) {
  #pins-container {
    max-width: 2535px;
  }
}
@media screen and (min-width: 2838px) {
  #pins-container {
    max-width: 2790px;
  }
}
</style>
